# site properties and page defaults
title: 3D Epigenome in Cancer Group
subtitle: Epigenetics Research Laboratory, Garvan Institute of Medical Research
description: The focus of the group is to understand how the three-dimensional (3D) organization of DNA inside the nucleus relates to gene deregulation in cancer, including its cell-to-cell and temporal variability.
header: images/image_3D_Epigenome_in_Cancer.png
footer: images/background.jpg

# site social media and other links
links:
  email: j.achinger(at)garvan.org.au
  orcid: 0000-0002-2902-9371
  google-scholar: ETJoidYAAAAJ
  github: JoannaAch
  twitter: aachinger

### jekyll settings

# front matter defaults
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post

collections:
  # generate page for each member
  members:
    output: true
  # generate page for each post
  posts:
    output: true

# jekyll plugins
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at

# code block syntax highlighting
highlighter: rouge

# jekyll theme
theme: null

# sass settings
sass:
  sass_dir: _styles

# force jekyll to include certain files/folders
include:
  - _styles
  - _scripts

# force jekyll to exclude certain files/folders
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff
